language: node_js
node_js: 9

cache:
  directories:
    - node_modules

env:
  - CI=true

script:
  - npm test -- --coverage

before_deploy:
  - npm run build

deploy:
  provider: script
  script: node ./publish.js
  skip_cleanup: true
  on:
    branch: master
